# Pixelwise Image Segmentation
### Motivation
This problem will introduce you to understand pixel-wise image segmentation. The image
segmentation problem is a core vision problem with a longstanding history of research. Historically, this problem has been studied in the unsupervised setting as a clustering problem:
given an image, produce a pixelwise prediction that segments the image into coherent clusters
corresponding to objects in the image. In this case, you are expected to learn about how to
segment iris area in the given eye images.

### Problem Statement
In this problem, we are providing you Data folder for eye images and corresponding masks in
separate Mask folder. Your task is to learn the model in such a way that it should take eye as
input image and produce mask for iris (which is in contour shape).

### Submission
Your model will be tested on separate iris images. For testing, you have to code in such
a way that it should provide predicted masks for the given input images. Your task is to
write script to save predicted mask for each testing image in a predicted mask folder.



In [1]:
# Imports

import tensorflow as tf
import numpy as np
import cv2
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from PIL import Image
import os

In [2]:
# Read data

im_train = np.load("./prep_data/im_train.npy")
im_test = np.load("./prep_data/im_test.npy")
mask_train = np.load("./prep_data/mask_train.npy")
mask_test = np.load("./prep_data/mask_test.npy")

In [3]:
print(im_train[0][0])

[[120 132 187]
 [120 132 186]
 [121 133 185]
 ...
 [114 134 190]
 [113 134 190]
 [113 134 190]]


## Encoder

In [ ]:
def my_encoder():
    