In [7]:
import numpy as np
import time

tic = time.time()
G = 6.67e5
threshold = 0.1
ts = 1e-4                                                 #time step
M = np.load("../q2_input/masses.npy")       #masses
X = np.load("../q2_input/positions.npy")     #postions
V = np.load("../q2_input/velocities.npy")    #velocities
A = np.zeros((100,100))
chk = np.ones((100,100))

def calcAccl():
    global A
    global chk
#     global X
    
    D = X.reshape(1, 100, 2)
    D = np.repeat(D, 100, axis=0)

    temp = np.repeat(X, 100, axis=0)
    temp = temp.reshape(100,100,2)
    D = D - temp
    temp = D
    
#     print(M)
    chk = np.linalg.norm(D, axis=2)
    np.fill_diagonal(chk, 1)
    D = np.power(chk, 3)

#     D = (D * M.reshape(1,100)).reshape(100, 100, 1)
    D = D.reshape(100,100,1)
#     print(np.repeat(M.reshape(1,100,1), 2, axis=2))
    temp = temp * np.repeat(M.reshape(1,100,1), 2, axis=2)
    D = G * (temp / np.repeat(D, 2, axis=2))
    D = np.sum(D, axis=1)

    A = D

iter = 0
while True:
    val = chk.min()
    print(val)
    if val < threshold:
        #print to files
        np.save('finalPosCmp.npy', X, allow_pickle = False)
        np.save('finalVelCmp.npy', V, allow_pickle = False)
        print("iter = %d" % iter)
        break
    calcAccl()
    X = X + V * ts + 0.5 * A * ts * ts
    V = V + A * ts
    iter += 1
        
print("--- %s seconds ---" % (time.time() - tic))

1.0
[[[   2.37820595    2.37820595]
  [   2.23605677    2.23605677]
  [   1.47192288    1.47192288]
  [1000.         1000.        ]
  [   2.85555393    2.85555393]
  [   1.67916141    1.67916141]
  [   1.8818654     1.8818654 ]
  [   1.85543336    1.85543336]
  [   2.32557204    2.32557204]
  [   2.74368864    2.74368864]
  [   1.40606186    1.40606186]
  [   1.71087831    1.71087831]
  [   2.04558753    2.04558753]
  [   2.31727704    2.31727704]
  [   1.07877804    1.07877804]
  [   2.31259451    2.31259451]
  [   1.57809968    1.57809968]
  [   1.6675107     1.6675107 ]
  [   2.86056548    2.86056548]
  [   2.90554899    2.90554899]
  [   1.59800102    1.59800102]
  [   1.0223679     1.0223679 ]
  [   1.65765379    1.65765379]
  [   1.03758102    1.03758102]
  [   1.11736251    1.11736251]
  [   1.00730615    1.00730615]
  [   1.7905472     1.7905472 ]
  [   1.96742351    1.96742351]
  [   1.04278251    1.04278251]
  [   2.60345951    2.60345951]
  [   1.08699894    1.08699894]
  [ 

0.4502874235132394
[[[   2.37820595    2.37820595]
  [   2.23605677    2.23605677]
  [   1.47192288    1.47192288]
  [1000.         1000.        ]
  [   2.85555393    2.85555393]
  [   1.67916141    1.67916141]
  [   1.8818654     1.8818654 ]
  [   1.85543336    1.85543336]
  [   2.32557204    2.32557204]
  [   2.74368864    2.74368864]
  [   1.40606186    1.40606186]
  [   1.71087831    1.71087831]
  [   2.04558753    2.04558753]
  [   2.31727704    2.31727704]
  [   1.07877804    1.07877804]
  [   2.31259451    2.31259451]
  [   1.57809968    1.57809968]
  [   1.6675107     1.6675107 ]
  [   2.86056548    2.86056548]
  [   2.90554899    2.90554899]
  [   1.59800102    1.59800102]
  [   1.0223679     1.0223679 ]
  [   1.65765379    1.65765379]
  [   1.03758102    1.03758102]
  [   1.11736251    1.11736251]
  [   1.00730615    1.00730615]
  [   1.7905472     1.7905472 ]
  [   1.96742351    1.96742351]
  [   1.04278251    1.04278251]
  [   2.60345951    2.60345951]
  [   1.08699894    1

[[[   2.37820595    2.37820595]
  [   2.23605677    2.23605677]
  [   1.47192288    1.47192288]
  [1000.         1000.        ]
  [   2.85555393    2.85555393]
  [   1.67916141    1.67916141]
  [   1.8818654     1.8818654 ]
  [   1.85543336    1.85543336]
  [   2.32557204    2.32557204]
  [   2.74368864    2.74368864]
  [   1.40606186    1.40606186]
  [   1.71087831    1.71087831]
  [   2.04558753    2.04558753]
  [   2.31727704    2.31727704]
  [   1.07877804    1.07877804]
  [   2.31259451    2.31259451]
  [   1.57809968    1.57809968]
  [   1.6675107     1.6675107 ]
  [   2.86056548    2.86056548]
  [   2.90554899    2.90554899]
  [   1.59800102    1.59800102]
  [   1.0223679     1.0223679 ]
  [   1.65765379    1.65765379]
  [   1.03758102    1.03758102]
  [   1.11736251    1.11736251]
  [   1.00730615    1.00730615]
  [   1.7905472     1.7905472 ]
  [   1.96742351    1.96742351]
  [   1.04278251    1.04278251]
  [   2.60345951    2.60345951]
  [   1.08699894    1.08699894]
  [   1.

[[[   2.37820595    2.37820595]
  [   2.23605677    2.23605677]
  [   1.47192288    1.47192288]
  [1000.         1000.        ]
  [   2.85555393    2.85555393]
  [   1.67916141    1.67916141]
  [   1.8818654     1.8818654 ]
  [   1.85543336    1.85543336]
  [   2.32557204    2.32557204]
  [   2.74368864    2.74368864]
  [   1.40606186    1.40606186]
  [   1.71087831    1.71087831]
  [   2.04558753    2.04558753]
  [   2.31727704    2.31727704]
  [   1.07877804    1.07877804]
  [   2.31259451    2.31259451]
  [   1.57809968    1.57809968]
  [   1.6675107     1.6675107 ]
  [   2.86056548    2.86056548]
  [   2.90554899    2.90554899]
  [   1.59800102    1.59800102]
  [   1.0223679     1.0223679 ]
  [   1.65765379    1.65765379]
  [   1.03758102    1.03758102]
  [   1.11736251    1.11736251]
  [   1.00730615    1.00730615]
  [   1.7905472     1.7905472 ]
  [   1.96742351    1.96742351]
  [   1.04278251    1.04278251]
  [   2.60345951    2.60345951]
  [   1.08699894    1.08699894]
  [   1.

[[[   2.37820595    2.37820595]
  [   2.23605677    2.23605677]
  [   1.47192288    1.47192288]
  [1000.         1000.        ]
  [   2.85555393    2.85555393]
  [   1.67916141    1.67916141]
  [   1.8818654     1.8818654 ]
  [   1.85543336    1.85543336]
  [   2.32557204    2.32557204]
  [   2.74368864    2.74368864]
  [   1.40606186    1.40606186]
  [   1.71087831    1.71087831]
  [   2.04558753    2.04558753]
  [   2.31727704    2.31727704]
  [   1.07877804    1.07877804]
  [   2.31259451    2.31259451]
  [   1.57809968    1.57809968]
  [   1.6675107     1.6675107 ]
  [   2.86056548    2.86056548]
  [   2.90554899    2.90554899]
  [   1.59800102    1.59800102]
  [   1.0223679     1.0223679 ]
  [   1.65765379    1.65765379]
  [   1.03758102    1.03758102]
  [   1.11736251    1.11736251]
  [   1.00730615    1.00730615]
  [   1.7905472     1.7905472 ]
  [   1.96742351    1.96742351]
  [   1.04278251    1.04278251]
  [   2.60345951    2.60345951]
  [   1.08699894    1.08699894]
  [   1.

[[[   2.37820595    2.37820595]
  [   2.23605677    2.23605677]
  [   1.47192288    1.47192288]
  [1000.         1000.        ]
  [   2.85555393    2.85555393]
  [   1.67916141    1.67916141]
  [   1.8818654     1.8818654 ]
  [   1.85543336    1.85543336]
  [   2.32557204    2.32557204]
  [   2.74368864    2.74368864]
  [   1.40606186    1.40606186]
  [   1.71087831    1.71087831]
  [   2.04558753    2.04558753]
  [   2.31727704    2.31727704]
  [   1.07877804    1.07877804]
  [   2.31259451    2.31259451]
  [   1.57809968    1.57809968]
  [   1.6675107     1.6675107 ]
  [   2.86056548    2.86056548]
  [   2.90554899    2.90554899]
  [   1.59800102    1.59800102]
  [   1.0223679     1.0223679 ]
  [   1.65765379    1.65765379]
  [   1.03758102    1.03758102]
  [   1.11736251    1.11736251]
  [   1.00730615    1.00730615]
  [   1.7905472     1.7905472 ]
  [   1.96742351    1.96742351]
  [   1.04278251    1.04278251]
  [   2.60345951    2.60345951]
  [   1.08699894    1.08699894]
  [   1.

[[[   2.37820595    2.37820595]
  [   2.23605677    2.23605677]
  [   1.47192288    1.47192288]
  [1000.         1000.        ]
  [   2.85555393    2.85555393]
  [   1.67916141    1.67916141]
  [   1.8818654     1.8818654 ]
  [   1.85543336    1.85543336]
  [   2.32557204    2.32557204]
  [   2.74368864    2.74368864]
  [   1.40606186    1.40606186]
  [   1.71087831    1.71087831]
  [   2.04558753    2.04558753]
  [   2.31727704    2.31727704]
  [   1.07877804    1.07877804]
  [   2.31259451    2.31259451]
  [   1.57809968    1.57809968]
  [   1.6675107     1.6675107 ]
  [   2.86056548    2.86056548]
  [   2.90554899    2.90554899]
  [   1.59800102    1.59800102]
  [   1.0223679     1.0223679 ]
  [   1.65765379    1.65765379]
  [   1.03758102    1.03758102]
  [   1.11736251    1.11736251]
  [   1.00730615    1.00730615]
  [   1.7905472     1.7905472 ]
  [   1.96742351    1.96742351]
  [   1.04278251    1.04278251]
  [   2.60345951    2.60345951]
  [   1.08699894    1.08699894]
  [   1.